{% set name = "ypywidgets" %}
{% set version = "0.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78ee67a034fa7131197a5e42ba86c9e9428767a4176dc10e5cf6e4d409132c1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - comm >=0.1.4,<1
    - pycrdt >=0.9.0,<0.11.0
    - reacttrs >=0.2.1,<0.3.0

test:
  imports:
    - ypywidgets
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/QuantStack/ypywidgets
  summary: Y-based Jupyter widgets for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/QuantStack/ypywidgets

extra:
  recipe-maintainers:
    - martinRenou
    - davidbrochart
