{% set name = "ypywidgets" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1d788ef1ed7ff39d4c7db96c6265ba1503c6e2dfbd3720e20bbc37e97398e9f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
  run:
    - python >=3.8
    - comm >=0.1.4,<1
    - pycrdt >=0.8.30,<0.9.0
    - reacttrs >=0.2.1,<0.3.0

test:
  imports:
    - ypywidgets
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/davidbrochart/ypywidgets
  summary: Y-based Jupyter widgets for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/davidbrochart/ypywidgets

extra:
  recipe-maintainers:
    - martinRenou
    - davidbrochart
