{% set name = "ypywidgets" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5cd97154986c39a4fb9406b54af1b94e5e5172621d229a25e2cfaa7735a36b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - comm >=0.1.4,<1
    - pycrdt >=0.9.0,<0.15.0
    - reacttrs >=0.2.1,<0.3.0

test:
  imports:
    - ypywidgets
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/QuantStack/ypywidgets
  summary: Y-based Jupyter widgets for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/QuantStack/ypywidgets

extra:
  recipe-maintainers:
    - martinRenou
    - davidbrochart
