{% set name = "ypywidgets" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acef0bcffff6469cfef4a760392d4fe301168a3809f00bc525f6a103f06d9016

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - comm >=0.1.4,<1
    - pycrdt >=0.9.0,<0.11.0
    - reacttrs >=0.2.1,<0.3.0

test:
  imports:
    - ypywidgets
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/QuantStack/ypywidgets
  summary: Y-based Jupyter widgets for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/QuantStack/ypywidgets

extra:
  recipe-maintainers:
    - martinRenou
    - davidbrochart
